server:
  port: 8082
  servlet:
    context-path: /User
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driverClassName: org.h2.Driver
    password: null
    url: jdbc:h2:mem:testdb
    username: sa    
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
 